version: "3.3"

services:
  base-server:
    build:
      context: ./base-server
      dockerfile: Dockerfile
    ports:
      - "3015:3015"
    environment:
      - NODE_ENV=production

  peer-server:
    build:
      context: ./peer-server
      dockerfile: Dockerfile
    ports:
      - "3016:3016"
    environment:
      - NODE_ENV=production
